import {DATA} from '../../data/content.js';
import {byId} from '../game/game.js';
import {defaults} from '../save/storage.js';
export const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class Interface{
 constructor(game,renderer,storage,settings,save){this.g=game;this.renderer=renderer;this.storage=storage;this.settings=settings;this.save=save;this.home=document.querySelector('#home');this.play=document.querySelector('#play');this.dialog=document.querySelector('#dialog');this.body=document.querySelector('#dialog-body');this.screen='home';this.selection=0;this.mode='classic';this.shop=false;this.event=null;this.installPrompt=null;
 document.querySelector('#close').onclick=()=>this.close();this.dialog.addEventListener('click',e=>{if(e.target===this.dialog)this.close();});this.dialog.addEventListener('cancel',()=>{this.shop=false;});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-command]');if(!el)return;this.command(el.dataset.command,el.dataset.value);});
 window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();this.installPrompt=event;if(this.screen==='home')this.main();});
 this.g.onInteract=o=>this.interaction(o);this.g.onDeath=()=>{const dead=this.g.run;setTimeout(()=>{if(this.g.run===dead&&dead.over&&this.screen!=='selection')this.results();},80);};this.g.listeners.push(()=>{this.update();this.save();});this.main();
 }
 modal(title,html){document.querySelector('#dialog-title').textContent=title;this.body.innerHTML=html;if(!this.dialog.open)this.dialog.showModal();}
 close(){if(this.g.run)this.g.run.lastTime=Date.now();this.dialog.close();this.shop=false;this.event=null;this.g.audio.unlock();}
 button(text,command,value='',css=''){return `<button class="${css}" data-command="${command}" data-value="${escape(value)}">${text}</button>`;}
 icon(id){return `<span class="pixelicon" style="background-position:-${(id%16)*32}px -${Math.floor(id/16)*32}px"></span>`;}
 main(){this.screen='home';this.body.dataset.kind='';this.home.hidden=false;this.play.hidden=true;this.g.audio.mode='menu';
 this.home.innerHTML=`<img class="logo" src="./assets/ui/logo.svg" alt="Riftbound: Endless Depths"><p class="tag">La grieta recuerda. Cada paso importa.</p><div class="menu">${this.g.run&&!this.g.run.over?this.button('CONTINUAR','resume','','primary'):''}${this.button('JUGAR','new','','primary')}${this.button('PERSONAJES','characters')}${this.button('INVENTARIO','inventory')}${this.button('LOGROS','achievements')}${this.button('RÉCORDS LOCALES','records')}${this.button('AJUSTES','settings')}${this.button('CRÉDITOS','credits')}${this.installPrompt?this.button('INSTALAR PWA','install'):''}</div><p class="center muted">${this.g.meta.shards} fragmentos · mejora permanente ${this.g.meta.upgrade}<br>Una mano. Por turnos. Sin conexión tras la primera carga.</p><div class="menu">${this.button(`ANCLA PERMANENTE · ${5+this.g.meta.upgrade*5} fragmentos`,'upgrade')}<small>+3 de salud inicial por nivel de ancla. Sin pagos reales.</small></div>`;
 }
 selectionScreen(){this.screen='selection';this.home.hidden=false;this.play.hidden=true;
 this.home.innerHTML=`<h1 class="center">Elige tu vínculo</h1><p class="center muted">Tres clases iniciales; las otras se desbloquean por bajas acumuladas.</p><div class="cards">${DATA.classes.map((c,i)=>{const unlocked=this.g.meta.unlocked.includes(i);return `<article class="card ${this.selection===i?'selected':''}"><span class="portrait" style="background-position:-${i*48}px 0"></span><h2>${c.id}</h2><small>${c.name} · ${c.weapon}</small><p style="clear:both;padding-top:10px">HP ${c.hp} · ATQ ${c.attack} · DEF ${c.defense}<br>Energía ${c.resource} · CRIT ${Math.round(c.crit*100)}%</p><p>${c.strength}</p><small>${c.weakness}</small><p>${c.skills.map(s=>s.name).join(' / ')}</p>${unlocked?this.button(this.selection===i?'SELECCIONADO':'ELEGIR','select',i):`<p class="notice">Requiere ${c.unlock} bajas históricas.</p>`}</article>`;}).join('')}</div><div class="menu"><label>Modo<select id="mode"><option value="classic" ${this.mode==='classic'?'selected':''}>CLASSIC · un ancla</option><option value="hardcore" ${this.mode==='hardcore'?'selected':''}>HARDCORE · muerte definitiva</option></select></label><small>CLASSIC permite una resurrección perdiendo la mitad del oro. HARDCORE elimina el progreso de la run al morir.</small><label>Seed<input id="seed" maxlength="80" placeholder="Aleatoria"></label>${this.button('COMENZAR','start','','primary')}${this.button('VOLVER','home')}</div>`;
 document.querySelector('#mode').onchange=e=>this.mode=e.target.value;
 }
 resume(){if(!this.g.run||this.g.run.over)return;this.close();this.screen='play';this.home.hidden=true;this.play.hidden=false;this.g.run.lastTime=Date.now();this.g.audio.unlock();this.renderer.initialized=false;requestAnimationFrame(()=>this.renderer.resize());this.update();}
 update(){const g=this.g;if(!g.run)return;const p=g.p,s=g.stats();const percent=(v,max)=>Math.max(0,Math.min(100,v/max*100));document.querySelector('#hud').innerHTML=`<div>HP ${Math.ceil(p.hp)} / ${s.hp}${p.shield?` · Escudo ${Math.round(p.shield)}`:''}<div class="bar hp"><i style="width:${percent(p.hp,s.hp)}%"></i></div></div><div>ENERGÍA ${Math.floor(p.mp)} / ${s.resource}<div class="bar mp"><i style="width:${percent(p.mp,s.resource)}%"></i></div></div><div>NIVEL ${p.level} · XP ${p.xp}/${g.xpGoal()}<div class="bar xp"><i style="width:${percent(p.xp,g.xpGoal())}%"></i></div></div><div>ORO ${p.gold} · ${g.run.mode.toUpperCase()}<br><small>${g.c.id} · TURNO ${g.run.turn}</small></div>`;
 document.querySelector('#log').innerHTML=g.messages.slice(0,2).map(escape).join('<br>');document.querySelector('#skillbar').innerHTML=g.c.skills.map((sk,i)=>`<button data-skill="${i}" aria-label="${sk.name}" ${p.skillRanks[i]===0?'disabled':''}>${['I','II','III'][i]}${p.cooldowns[i]>0?` (${p.cooldowns[i]})`:''}<br>${sk.cost} E</button>`).join('');
 const boss=g.w.enemies.find(e=>e.boss&&g.visible(e));g.audio.mode=this.screen==='play'?(boss?'boss':g.w.biome):'menu';
 if(this.dialog.open){const kind=this.body.dataset.kind;if(kind==='inventory')this.inventory(this.shop);if(kind==='skills')this.skills();if(kind==='quests')this.quests();}
 }
 characters(){this.modal('Vínculos y memoria',`<div class="stack">${DATA.classes.map((c,i)=>`<div class="item">${this.icon(c.sprite)}<strong>${c.id}</strong> · ${this.g.meta.unlocked.includes(i)?'Desbloqueado':`${c.unlock} bajas requeridas`}<p>${c.strength}</p></div>`).join('')}</div><h3>Últimos personajes</h3>${(this.g.meta.characters||[]).slice(0,10).map(c=>`<p>${DATA.classes[c.classIndex].id} · ${c.mode} · ${new Date(c.date).toLocaleDateString()}</p>`).join('')||'<p>Aún no hay personajes.</p>'}`);this.body.dataset.kind='';}
 inventory(shop=false){const g=this.g;if(!g.run||g.run.over){this.modal('Inventario','<p>No hay una run activa. El equipo es propio de cada run.</p>');this.body.dataset.kind='';return;}this.shop=shop;const s=g.stats();
 let html=`<p>HP ${s.hp} · ATQ ${s.attack.toFixed(1)} · DEF ${s.defense.toFixed(1)} · VEL ${s.speed.toFixed(2)}<br>CRIT ${(s.crit*100).toFixed(0)}% · EVA ${(s.evasion*100).toFixed(0)}% · REGEN ${s.regen.toFixed(2)}<br>ENERGÍA ${s.resource} · ORO ${g.p.gold} · Objetos ${g.p.inventory.length}/60</p><h3>Equipo</h3>${Object.entries(g.p.equipment).map(([slot,item])=>`<div class="item">${{weapon:'Arma',armor:'Armadura',accessory:'Accesorio'}[slot]}: ${item?this.itemDetails(item):'Vacío'}</div>`).join('')}<h3>Mochila</h3>`;
 html+=g.p.inventory.map(item=>{const def=byId(item.base);const old=g.p.equipment[def.slot];const comparison=def.slot==='consumable'?'':this.compare(item,old);return `<div class="item">${this.itemDetails(item)}${comparison}<div class="row">${this.button(def.slot==='consumable'?'USAR':'EQUIPAR','equip',item.uid,'primary')}${this.button('TIRAR','drop',item.uid)}${shop?this.button(`VENDER ${Math.round(def.price*DATA.rarities[item.rarity].mult*.4*(g.hasEffect('gold')?1.25:1))}`,'sell',item.uid):''}</div></div>`;}).join('')||'<p>Mochila vacía.</p>';
 if(shop){html+=`<h3>Mercado de Liria</h3><p>Las compras consumen un turno: vigila a los enemigos cercanos.</p>`;const stock=['i54','i55','i56','i57',`i${(g.run.depth*3)%18}`,`i${18+g.run.depth%18}`,`i${36+g.run.depth%18}`];html+=stock.map(id=>{const item=byId(id);const price=item.price;return `<div class="item">${this.icon(item.sprite)}${item.name}<p>${item.desc}</p>${this.button(`COMPRAR · ${price} oro`,'buy',`${id}:${price}`)}</div>`;}).join('');}
 this.modal(shop?'Comerciante · comprar y vender':'Mochila y equipo',html);this.body.dataset.kind='inventory';
 }
 itemDetails(item){const def=byId(item.base),r=DATA.rarities[item.rarity],mult=r.mult*item.power;return `${this.icon(def.sprite)}<strong style="color:${r.color}">${escape(genericName(item))}</strong><p>${def.desc}</p><small>${Object.entries(def.stats).map(([k,v])=>`${k.toUpperCase()} ${Math.abs(v)<1?(v*mult*100).toFixed(0)+'%':(v*mult).toFixed(1)}`).join(' · ')}</small>`;}
 compare(item,old){const def=byId(item.base),mult=DATA.rarities[item.rarity].mult*item.power,previous=old?byId(old.base).stats:{};const om=old?DATA.rarities[old.rarity].mult*old.power:0;const keys=new Set([...Object.keys(def.stats),...Object.keys(previous)]);return `<p><small>Comparación: ${[...keys].map(k=>{const n=(def.stats[k]||0)*mult-(previous[k]||0)*om;return `<span style="color:${n>=0?'#95d4ac':'#e99eac'}">${k} ${n>=0?'+':''}${n.toFixed(2)}</span>`;}).join(' · ')}</small></p>`;}
 skills(){if(!this.g.run||this.g.run.over)return;const p=this.g.p;const names=['Fuerza del vínculo','Piel del umbral','Pulso vital'];this.modal('Árbol de habilidades',`<p>Puntos disponibles: <strong>${p.points}</strong>. Cada nivel concede dos puntos.</p><p>Activas: ramas I, II, III. Pasivas: fuerza, defensa y regeneración. Cada rama alcanza rango 5.</p><div class="cards">${Array.from({length:6},(_,i)=>{const sk=this.g.c.skills[i];const name=sk?sk.name:names[i-3];const desc=sk?`${sk.desc} Coste: ${sk.cost} E. Recarga base: ${sk.cooldown} turnos.`:['+2 ataque por rango.','+1 defensa por rango.','+0,2 regeneración por turno y rango.'][i-3];return `<div class="card"><h3>${i+1}. ${name}</h3><p>${desc}</p><p>Rango ${p.skillRanks[i]} / 5</p>${this.button('MEJORAR · 1 punto','train',i)}${sk&&p.skillRanks[i]>0?this.button('USAR','skill',i):''}</div>`;}).join('')}</div>`);this.body.dataset.kind='skills';}
 quests(){if(!this.g.run||this.g.run.over)return;const r=this.g.run;this.modal('Misiones del cartógrafo',DATA.quests.map(q=>{const n=r.questProgress[q.metric]||0,done=r.claimed.includes(q.id);return `<div class="item"><h3>${q.name}</h3><p>${q.metric}: ${Math.min(n,q.target)} / ${q.target}<br>Recompensa: ${q.gold} oro, ${q.xp} XP.</p>${done?'<span class="chip">RECLAMADA</span>':n>=q.target?this.button('RECLAMAR','quest',q.id,'primary'):'<small>En progreso.</small>'}</div>`;}).join(''));this.body.dataset.kind='quests';}
 achievements(){const m=this.g.meta;this.modal(`Logros · ${m.achievements.length}/${DATA.achievements.length}`,DATA.achievements.map(a=>`<div class="item"><strong>${m.achievements.includes(a.id)?'COMPLETADO · ':''}${a.name}</strong><p>${a.metric}: ${Math.min(m.stats[a.metric]||0,a.target)} / ${a.target} · ${a.reward} fragmentos</p></div>`).join(''));this.body.dataset.kind='';}
 records(){const records=this.g.meta.records;this.modal('Clasificación local',`<p>Ordenada por sector y pasos. Almacenada solo en este navegador.</p><div class="tablewrap"><table><thead><tr><th>Clase</th><th>Sector / pasos</th><th>Nivel</th><th>Bajas</th><th>Oro</th><th>Jefes</th><th>Tiempo</th></tr></thead><tbody>${records.map(r=>`<tr><td>${r.class}<br>${r.mode}</td><td>${r.depth} / ${r.distance}</td><td>${r.level}</td><td>${r.kills}</td><td>${r.gold}</td><td>${r.bosses}</td><td>${Math.floor(r.duration/60)}m ${r.duration%60}s</td></tr>`).join('')}</tbody></table></div>${records.length?'':'<p>Todavía no hay resultados.</p>'}`);this.body.dataset.kind='';}
 pause(){this.modal('Pausa',`<div class="stack">${this.button('CONTINUAR','close','','primary')}${this.button('GUARDAR Y VOLVER AL MENÚ','menu')}${this.button('AJUSTES','settings')}${this.button('ABANDONAR RUN','abandon','','danger')}</div><p class="muted">El mundo solo avanza con una acción. Ningún enemigo actúa mientras estás en los menús.</p>`);this.body.dataset.kind='';}
 results(){const r=this.g.run;if(!r)return;this.screen='results';this.modal('La grieta guarda tu memoria',`<h3>${this.g.c.id} · ${r.mode.toUpperCase()}</h3><p>Sector ${r.depth} · nivel ${this.g.p.level}<br>${r.metrics.steps} pasos · ${r.metrics.kills} enemigos<br>${r.metrics.bosses} jefes · ${r.metrics.goldEarned} oro recogido<br>${Math.floor(r.elapsed/60000)} minutos · seed ${escape(r.seed)}</p><p>Tu equipo y niveles de run se pierden. Logros, desbloqueos, fragmentos y récords se conservan.</p><div class="row">${this.button('NUEVA RUN','new','','primary')}${this.button('MENÚ','menu')}</div>`);this.body.dataset.kind='';this.save();}
 settingsScreen(){this.modal('Ajustes',`<label>Música<input type="checkbox" data-setting="music" ${this.settings.music?'checked':''}></label><label>Efectos de sonido<input type="checkbox" data-setting="sfx" ${this.settings.sfx?'checked':''}></label><label>Volumen<input type="range" min="0" max="1" step=".05" value="${this.settings.volume}" data-setting="volume"></label><label>Vibración opcional<input type="checkbox" data-setting="haptics" ${this.settings.haptics?'checked':''}></label><label>Reducir efectos y movimiento<input type="checkbox" data-setting="reduced" ${this.settings.reduced?'checked':''}></label><label>Calidad<select data-setting="quality"><option value="normal" ${this.settings.quality==='normal'?'selected':''}>Normal</option><option value="low" ${this.settings.quality==='low'?'selected':''}>Ahorro</option></select></label><label>Tamaño de interfaz<input type="range" min=".8" max="1.4" step=".1" value="${this.settings.ui}" data-setting="ui"></label><label>Idioma<select data-setting="language"><option value="es">Español</option></select></label><small>Datos y cadenas separados para futura traducción; solo español disponible.</small><p class="notice">El guardado pertenece a este origen y navegador. Borrar los datos del sitio elimina también el progreso.</p><div class="row">${this.button('RESTAURAR AJUSTES','reset-settings')}${this.button('ELIMINAR TODOS LOS DATOS','delete','','danger')}</div>`);this.body.dataset.kind='';
 this.body.querySelectorAll('[data-setting]').forEach(input=>input.oninput=()=>{this.settings[input.dataset.setting]=input.type==='checkbox'?input.checked:input.type==='range'?Number(input.value):input.value;this.applySettings();this.save();});
 }
 applySettings(){document.documentElement.style.setProperty('--ui',this.settings.ui);this.g.audio.update();if(this.settings.quality==='low')this.settings.reduced=true;this.renderer.resize();}
 interaction(obj){this.event=obj;if(obj.type==='event'){const definitions={altar:['Altar del fragmento','Entregar 20% de salud: +45 XP','Aceptar energía: +10 E'],cursed:['Cofre bajo juramento','Abrir: equipo épico, debilidad y un enemigo','Romper el sello: equipo inusual'],shrine:['Fuente dormida','Pagar 25 oro: curación completa','Beber del borde: +8 HP'],fork:['Dos grietas','Cruzar: +35 oro y saltar dos sectores','Ruta segura: +12 oro'],secret:['La testigo sin rostro','Sangrar: +2 fragmentos permanentes','Escuchar: +20 oro'],cache:['Suministros de un viajero','Recoger tónico de salud','Recoger 25 oro'],champion:['Desafío de piedra','Despertar campeón: +45 oro, combate peligroso','Rechazar: +5 energía']};const [title,a,b]=definitions[obj.event];this.modal(title,`<p>Tu elección tiene efecto real. Resolverla consume un turno.</p><div class="stack">${this.button(a,'event',0,'primary')}${this.button(b,'event',1)}</div>`);this.body.dataset.kind='';return;}
 const type=obj.npc;if(type==='merchant'){this.inventory(true);return;}
 const data={healer:['Ena, la remendadora','Una cura completa por 30 oro.','Curar · 30 oro','heal-npc'],smith:['Taro, herrero de ecos','Mejora permanentemente el arma de esta run (+15% de potencia), por 40 oro.','Templar arma · 40 oro','smith'],trainer:['Irel, guardiana del pulso','Compra un punto de habilidad por 60 oro.','Entrenar · 60 oro','trainer'],story:['Neris, cartógrafa de la grieta','Cada corona mantiene cerrado un umbral. Las casillas rojizas anuncian el ataque del guardián: debes salir antes del siguiente turno.','Ver misiones','quests'],secret:['Ulo, archivista oculto','Intercambia 80 oro por tres fragmentos permanentes.','Intercambiar · 80 oro','secret-npc']}[type];this.modal(data[0],`<p>${data[1]}</p>${this.button(data[2],data[3],'','primary')}`);this.body.dataset.kind='';
 }
 credits(){this.modal('Créditos y licencias',`<h3>Riftbound: Endless Depths</h3><p>Proyecto original creado en esta conversación. Pixel art geométrico, interfaz, iconos y audio sintetizado localmente. No contiene recursos descargados, música comercial ni assets del juego de referencia.</p><p>Sin dependencias externas. Sin analítica. Sin anuncios. Sin compras reales.</p><p>Consulta ASSET_LICENSES.md, LICENSE y VALIDATION.md del paquete para licencias y límites de verificación.</p><p>No se realizó investigación web ni una comprobación de marcas. Nombre provisional.</p><p>Controles: WASD/flechas, espacio atacar, E interactuar, Q esperar, 1/2/3 habilidades, I mochila, K árbol, M mapa, Esc pausa.</p>`);this.body.dataset.kind='';}
 async command(cmd,value){const g=this.g;g.audio.unlock();g.audio.sound('button');
 switch(cmd){case 'home':this.close();this.main();break;case 'new':if(g.run&&!g.run.over&&!confirm('Hay una run activa. ¿Abandonarla y crear otra?'))return;if(g.run&&!g.run.over)g.abandon();this.close();this.selectionScreen();break;case 'select':this.selection=Number(value);this.selectionScreen();break;case 'start':{const seed=document.querySelector('#seed').value.trim();g.start(this.selection,this.mode,seed);this.resume();this.save();break;}case 'resume':this.resume();break;case 'characters':this.characters();break;case 'inventory':this.inventory();break;case 'skills':this.skills();break;case 'quests':this.quests();break;case 'achievements':this.achievements();break;case 'records':this.records();break;case 'credits':this.credits();break;case 'settings':this.settingsScreen();break;case 'close':this.close();break;case 'menu':this.close();this.main();await this.save();break;case 'abandon':if(confirm('¿Terminar la run? Perderás su equipo y niveles.')){this.close();g.abandon();}break;
 case 'equip':g.equip(value);break;case 'drop':if(confirm('¿Dejar este objeto en el suelo?'))g.drop(value);break;case 'sell':if(this.shop)g.sell(value);break;case 'buy':if(this.shop){const [base,price]=value.split(':');g.buy(base,Number(price));}break;case 'train':g.train(Number(value));break;case 'skill':this.close();g.skill(Number(value));break;case 'quest':g.claimQuest(value);break;case 'event':{const event=this.event;this.close();if(event)g.resolveEvent(event,Number(value));break;}
 case 'upgrade':{const price=5+g.meta.upgrade*5;if(g.meta.shards>=price&&g.meta.upgrade<100){g.meta.shards-=price;g.meta.upgrade++;this.main();this.save();}else this.modal('Ancla permanente','<p>No hay suficientes fragmentos, o has alcanzado el máximo de 100 mejoras.</p>');break;}
 case 'install':if(this.installPrompt){await this.installPrompt.prompt();this.installPrompt=null;this.main();}break;
 case 'reset-settings':Object.assign(this.settings,defaults());this.applySettings();this.settingsScreen();this.save();break;
 case 'delete':if(confirm('¿Eliminar partida, logros, personajes y récords? Esta acción no se puede deshacer.')){await this.storage.clear();location.reload();}break;
 case 'heal-npc':if(g.p.gold>=30&&g.canAct()){this.close();g.p.gold-=30;g.p.hp=g.stats().hp;g.p.statuses={};g.log('Ena repara tu vínculo.');g.endTurn();}break;
 case 'smith':if(g.p.gold>=40&&g.p.equipment.weapon&&g.canAct()){this.close();g.p.gold-=40;g.p.equipment.weapon.power*=1.15;g.log('Taro refuerza tu arma.');g.endTurn();}break;
 case 'trainer':if(g.p.gold>=60&&g.canAct()){this.close();g.p.gold-=60;g.p.points++;g.log('Irel te concede un punto de habilidad.');g.endTurn();}break;
 case 'secret-npc':if(g.p.gold>=80&&g.canAct()){this.close();g.p.gold-=80;g.meta.shards+=3;g.log('Ulo preserva tres fragmentos.');g.endTurn();}break;
 }
 }
}
function genericName(item){return `${byId(item.base).name} · ${DATA.rarities[item.rarity].name}`;}
